services:
  db:
    image: postgres:16-alpine
    container_name: bndes-postgres
    environment:
      POSTGRES_DB: bndes_projetos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bndes_projetos"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    container_name: bndes-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bndes_projetos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_JWT_SECRET: "minha-chave-super-secreta-para-jwt-1234567890"
      APP_JWT_EXPIRATIONMINUTES: "120"
    ports:
      - "8080:8080"

volumes:
  pgdata:
