spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bndes_projetos}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

  flyway:
    baseline-on-migrate: true

app:
  jwt:
    secret: ${APP_JWT_SECRET:minha-chave-super-secreta-para-jwt-1234567890}
    expirationMinutes: ${APP_JWT_EXPIRATIONMINUTES:120}
